### ISSUE TITLE
python2.7 depends on `future` library 

### ISSUE THREAD

**Issue by williballenthin** [pachyderm/python-pachyderm#14]
`pfs_client.py` imports `builtins`, which is not present in a minimal python2.7 installation. This can be fixed by installing the `future` library via pip.

example:

```
root@0fb4804911b6:/opt# python
Python 2.7.12 (default, Nov 20 2017, 18:23:56)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pypachy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pypachy/__init__.py", line 1, in <module>
    from .pfs_client import PfsClient, DIR, FILE, NONE, JSON, LINE
  File "/usr/local/lib/python2.7/dist-packages/pypachy/pfs_client.py", line 3, in <module>
    from builtins import object
ImportError: No module named builtins
```

and to fix:

```
root@0fb4804911b6:/opt# pip install future
Collecting future
  Downloading future-0.16.0.tar.gz (824kB)
    100% |################################| 829kB 1.4MB/s
Building wheels for collected packages: future
  Running setup.py bdist_wheel for future ... done
  Stored in directory: /root/.cache/pip/wheels/c2/50/7c/0d83b4baac4f63ff7a765bd16390d2ab43c93587fac9d6017a
Successfully built future
Installing collected packages: future
Successfully installed future-0.16.0
root@0fb4804911b6:/opt# python
Python 2.7.12 (default, Nov 20 2017, 18:23:56)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pypachy
>>> exit
```

**Comment by frankhinek** [comment]
@williballenthin As specified in the package setup file, PyPachy requires:
'protobuf', 'grpcio', 'future>=0.14'

**Comment by williballenthin** [comment]
@frankhinek good point, I also see that line in the setup file now.

That being said, from a minimal Python 2.7 distribution, `pip install pypachy` is not sufficient:

```
λ docker run -it --rm --entrypoint /bin/bash python:2.7
root@a0d7544b5b02:/# pip install pypachy
Collecting pypachy
  Downloading pypachy-0.1.5.tar.gz (42kB)
    100% |████████████████████████████████| 51kB 1.3MB/s
Collecting protobuf (from pypachy)
  Downloading protobuf-3.5.1-cp27-cp27mu-manylinux1_x86_64.whl (6.4MB)
    100% |████████████████████████████████| 6.4MB 208kB/s
Collecting grpcio (from pypachy)
  Downloading grpcio-1.9.1-cp27-cp27mu-manylinux1_x86_64.whl (6.3MB)
    100% |████████████████████████████████| 6.3MB 198kB/s
Collecting six>=1.9 (from protobuf->pypachy)
  Downloading six-1.11.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/site-packages (from protobuf->pypachy)
Collecting enum34>=1.0.4 (from grpcio->pypachy)
  Downloading enum34-1.1.6-py2-none-any.whl
Collecting futures>=2.2.0 (from grpcio->pypachy)
  Downloading futures-3.2.0-py2-none-any.whl
Building wheels for collected packages: pypachy
  Running setup.py bdist_wheel for pypachy ... done
  Stored in directory: /root/.cache/pip/wheels/bb/c7/67/70b6bb5276c6aa7c8570a3246466906e0b754e3584eb77e55f
Successfully built pypachy
Installing collected packages: six, protobuf, enum34, futures, grpcio, pypachy
Successfully installed enum34-1.1.6 futures-3.2.0 grpcio-1.9.1 protobuf-3.5.1 pypachy-0.1.5 six-1.11.0
root@a0d7544b5b02:/# python
Python 2.7.14 (default, Nov  4 2017, 22:29:35)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pypachy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pypachy/__init__.py", line 1, in <module>
    from .pfs_client import PfsClient, DIR, FILE, NONE, JSON, LINE
  File "/usr/local/lib/python2.7/site-packages/pypachy/pfs_client.py", line 3, in <module>
    from builtins import object
ImportError: No module named builtins
```

looks like `grpcio` and `protobuf` are getting installed, but not `future`. let me dig into this a bit more.
