### ISSUE TITLE
python 2.7 import error

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/python-pachyderm#28]
We're unable to use the pip installation w python2.7

```
18-08-06[17:35:50]:~:0$python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import python_pachyderm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_pachyderm/__init__.py", line 5, in <module>
    from .pfs_client import PfsClient, DIR, FILE, NONE, JSON, LINE
  File "/usr/local/lib/python2.7/dist-packages/python_pachyderm/pfs_client.py", line 8, in <module>
    from .client.pfs.pfs_pb2 import *
ImportError: No module named pfs.pfs_pb2
>>> 
```

The same worked for python3. This looks like a relative import path error.

**Comment by ysimonson** [comment]
The latest on master is fixed now. Will make a pypi release soon.
