### ISSUE TITLE
Exception while committing

### ISSUE THREAD

**Issue by thedrow** [pachyderm/python-pachyderm#5]
One of my functional tests commits a file to a repo and it fails with the following error:
```
------------------------------------------------------------ Captured stdout call -------------------------------------------------------------
An exception occurred during an open commit. Trying to finish it (Currently a commit can't be cancelled)
------------------------------------------------------------ Captured stderr call -------------------------------------------------------------
ERROR:root:Exception iterating requests!
Traceback (most recent call last):
  File "/home/omer/Documents/Projects/drifter/drifter-collector/.tox/py36/lib/python3.6/site-packages/grpc/_channel.py", line 200, in consume_request_iterator
    request = next(request_iterator)
  File "/home/omer/Documents/Projects/drifter/drifter-collector/.tox/py36/lib/python3.6/site-packages/pypachy/client.py", line 295, in _blocks
    value=v[i:i + BUFFER_SIZE],
TypeError: unhashable type: 'slice'
```
It's not clear why the commit fails. Is this a bug or something that I am doing wrong?

**Comment by thedrow** [comment]
I'm using the latest pachyderm btw.
```
pachctl version
pachctl             1.4.6               
pachd               1.4.6
```

**Comment by kalugny** [comment]
Can you attach the calling code?

**Comment by thedrow** [comment]
It's pretty straight forward.

```python

def _get_raw_event_name(node_key, log_type):
    return '/%s/%s/%s' % (node_key, log_type, int(time.time()))


class EventsRepository:

    def __init__(self, connection):
        self.connection = connection

    def write_raw_event(self, node_key, log_type, event):
        event = {'node_key': node_key, 'event': event}

        with self.connection.commit('raw_events', 'master') as commit:
            self.connection.put_file_bytes(commit, _get_raw_event_name(node_key, log_type), event)
```

**Comment by thedrow** [comment]
I see it now. I'm passing a dict instead of bytes. That wasn't what I meant to do.
Still, the error should be clearer.

**Comment by kalugny** [comment]
A pull request is always appreciated ;)

**Comment by thedrow** [comment]
I'll investigate when I have the time to do so. In the meanwhile, keep this issue open :)

**Comment by ysimonson** [comment]
Going to close this out now. PRs are still welcome!
